package app.ma.scripts.schedule

import app.ma.scripts.common.RES_PATH
import app.ma.scripts.common.normalizeName
import java.io.File

val stationNameMapper = mapOf(
    "تجريش" to "Tajrish",
    "قيطريه" to "Gheytariyeh",
    "شهيدصدر" to "Shahid Sadr",
    "شهيد صدر" to "Shahid Sadr",
    "قلهك" to "Qolhak",
    "دكترشريعتي" to "Doctor Shariati",
    "دکتر شریعتی" to "Doctor Shariati",
    "ميرداماد" to "Mirdamad",
    "شهيدحقاني" to "Shahid Haghani",
    "شهيد حقانی" to "Shahid Haghani",
    "شهيدهمت" to "Shahid Hemmat",
    "مصليامامخميني(ره)" to "Mosalla-ye Imam Khomeini",
    "مصلی امام خمینی(ره)" to "Mosalla-ye Imam Khomeini",
    "شهيدبهشتي" to "Shahid Beheshti",
    "شهيد مفتح" to "Shahid Mofattah",
    "شهيدمفتح" to "Shahid Mofattah",
    "شهدايهفتتير" to "Shohada-ye Haftom-e Tir",
    "شهدای هفت تیر" to "Shohada-ye Haftom-e Tir",
    "طالقاني" to "Ayatollah Taleghani",
    "دروازهدولت" to "Darvazeh Dolat",
    "دروازه دولت" to "Darvazeh Dolat",
    "سعدي" to "Sa'adi",
    "امامخميني(ره)" to "Imam Khomeini",
    "امام خمینی(ره)" to "Imam Khomeini",
    "پانزدهخرداد" to "Panzdah-e Khordad",
    "پانزده خرداد" to "Panzdah-e Khordad",
    "خيام" to "Khayyam",
    "ميدانمحمديه" to "Meydan-e Mohammadiyeh",
    "میدان محمدیه" to "Meydan-e Mohammadiyeh",
    "شوش" to "Shoush",
    "پايانهجنوب" to "Payaneh Jonoub(Jonoub Terminal)",
    "پایانه جنوب" to "Payaneh Jonoub(Jonoub Terminal)",
    "شهيدبخارائي" to "Shahid Bokharaei",
    "شهید بخارائی" to "Shahid Bokharaei",
    "عليآباد" to "Aliabad",
    "علی آباد" to "Aliabad",
    "جوانمردقصاب" to "Javanmard-e Ghassab",
    "جوانمرد قصاب" to "Javanmard-e Ghassab",
    "شهرري" to "Shahr-e Rey",
    "شهر ری" to "Shahr-e Rey",
    "پالايشگاه" to "Palayeshgah",
    "شاهد" to "Shahed - BagherShahr",
    "حرممطهرامامخميني(ره)" to "Holy Shrine of Imam Khomeini",
    "حرم مطهر امام خمینی(ره)" to "Holy Shrine of Imam Khomeini",
    "كهريزك" to "Kahrizak",
    "فرودگاهامامخميني(ره)" to "Emam Khomeini Airport",
    "فرودگاه امام خمینی(ره)" to "Emam Khomeini Airport",
    "پرند" to "Shahr-e Parand",
    "شهرآفتاب" to "Namayeshgah-e Shahr-e Aftab",
    "تهران(صادقيه)" to "Tehran (Sadeghiyeh)",
    "صادقیه" to "Tehran (Sadeghiyeh)",
    "فرهنگسرا" to "Farhangsara",
    "طرشت" to "Tarasht",
    "دانشگاهشريف" to "Daneshgah-e Sharif",
    "دانشگاه علم و صنعت" to "Daneshgah-e Elm va Sanat",
    "دانشگاهعلموصنعت" to "Daneshgah-e Elm va Sanat",
    "شهيدباقري" to "Shahid Bagheri",
    "شهيدمدني" to "Shahid Madani",
    "امامحسين(ع)" to "Imam Hussein",
    "امام حسین(ع)" to "Imam Hussein",
    "سبلان" to "Sabalan",
    "فدک" to "Fadak",
    "جانبازان" to "Janbazan",
    "سرسبز" to "Sarsabz",
    "ملت" to "Mellat",
    "ميدانحر" to "Meydan-e Horr",
    "میدان حر" to "Meydan-e Horr",
    "حسنآباد" to "Hasan Abad",
    "شادمان" to "Shademan",
    "بهارستان" to "Baharistan",
    "دروازهشمیران" to "Darvazeh Shemiran",
    "دروازه شمیران" to "Darvazeh Shemiran",
    "تهرانپارس" to "Tehranpars",
    "دانشگاهامامعلي(ع)" to "Daneshgah-e Imam Ali",
    "شهیدنوابصفوی" to "Shahid Navab-e Safavi",
    "آزادگان" to "Azadegan",
    "قائم" to "Qa'em",
    "مهدیه" to "Mahdiyeh",
    "منیریه" to "Moniriyeh",
    "تئاترشهر" to "Teatr-e Shahr",
    "ميدانولیعصر(عج)" to "Meydan-e Hazrat Vali Asr",
    "میدان ولیعصر(عج)" to "Meydan-e Hazrat Vali Asr",
    "ميرزایشیرازی" to "Mirza-ye Shirazi",
    "سهروردی" to "Sohrevardi",
    "شهرکشريعتی" to "Shahrak-e Shariaty",
    "شهيدقدوسی" to "Shahid Ghodousi",
    "شهيدزينالدين" to "Shahid Zeynoddin",
    "شهيدمحلاتی" to "Shahid Mahallati",
    "شهيدصیادشیرازی" to "Shahid Sayyad Shirazi",
    "اقدسیه" to "Aghdasiyeh",
    "نوبنياد" to "Nobonyad",
    "هروی" to "Meydan-e Heravi",
    "ميدانجهاد" to "Meydan-e Jahad",
    "جوادیه" to "Javadiyeh",
    "عبدلآباد" to "Abdol Abad",
    "نعمتآباد" to "Nemat Abad",
    "حسينآباد" to "Hoseinabad",
    "راهآهن" to "Rahahan",
    "خواجهعبدالهانصاری" to "Khajeh Abdollah-e Ansari",
    "زمزم" to "Zamzam",
    "علامهجعفری" to "Allameh Jafari",
    "شهيدكلاهدوز" to "Shahid Kolahdooz",
    "بيمه" to "Bimeh",
    "پایانه1و2فرودگاهمهرآباد" to "Mehrabad Airport Terminal 1&2",
    "پایانه4و6فرودگاهمهرآباد" to "Mehrabad Airport Terminal 4&6",
    "ابنسينا" to "Ebn-e Sina",
    "ارمسبز" to "Eram-e Sabz",
    "توحيد" to "Towhid",
    "فردوسی" to "Ferdowsi",
    "ميدانآزادی" to "Meydan-e Azadi",
    "ميدانانقلاباسلامی" to "Meydan-e Enghelab-e Eslami",
    "ميدانشهدا" to "Meydan-e Shohada",
    "نبرد" to "Nabard",
    "نيروهوايی" to "Niroohavaii",
    "پيروزی" to "Piroozi",
    "دکترحبيب‌اله" to "Doctor Habibollah",
    "شهرکاکباتان" to "Shahrak-e Ekbatan",
    "استادمعین" to "Ostad Mo'in",
    "گلشهر" to "Golshahr",
    "كرج" to "Karaj",
    "گرمدره" to "Garmdareh",
    "وردآورد" to "Vardavard",
    "ايرانخودرو" to "Iran Khodro",
    "چيتگر" to "Chitgar",
    "ورزشگاهآزادی" to "Varzeshgah-e Azadi",
    "محمدشهر" to "Mohammadshahr",
    "اتمسفر" to "Atmosphere",
    "هشتگرد" to "Shahid Sepahbod Qasem Soleimani",
    "شهيدآرمان" to "Kouhsar",
    "دولتآباد" to "Shohada-ye Dowlat Abad",
    "شهيدرضايی" to "Shahid Rezaei",
    "شهيدستاری" to "Shahid Sattari",
    "اشرفیاصفهانی" to "Shahid Ashrafi Esfahani",
    "آيتالهکاشانی" to "Ayatollah Kashani",
    "اميرکبير" to "Amirkabir",
    "بعثت" to "Be'sat",
    "دانشگاهتربيتمدرس" to "Daneshgah-e Tarbiat Modarres",
    "شهدایکن" to "Shohada-ye Kan",
    "شهران" to "Shahran",
    "شهرزيبا" to "Shahr-e Ziba",
    "شهرکآزمايش" to "Shahrak-e Azmayesh",
    "مرزداران" to "Marzdaran",
    "ميدانخراسان" to "Meydan-e Khorasan",
    "کارگر" to "Karagar",
    "کيانه شهر" to "Kiyan Shahr",
    "يادگارامام" to "Yadegar-e Imam",
    "بسيج" to "Basij",
    "ميدانکتاب" to "Meydan-e Ketab",
    "ورزشگاهتختی" to "Varzeshgah-e Takhti",
    "مولوی" to "Mowlavi",
    "ميدانقيام" to "Meydan-e Ghiyam",
    "شهدای17شهريور" to "Shohada-ye Hefdah-e Shahrivar",
    "بريانک" to "Beryanak",
    "برجميلاد" to "Milad Tower",
    "مدافعانسلامت" to "Modafean-e Salamat",
    "شهيددادمان" to "Shahid Dadman",
    "آهنگ" to "Ahang",
    "رودکی" to "Roudaki",
    "ميدانصنعت" to "Meydan-e San'at",
    "هلالاحمر" to "Helal Ahmar",
    "کميل" to "Komeyl",
    "چهل‌تندولاب" to "Chehel Tan-e Doulab",
    "بوستانگفتگو" to "Boostan-e Goftegou",
    "کیانشهر" to "Kiyan Shahr",
    "بهارشیراز" to "Bahar Shiraz (Khanevadeh Hospital)",
    "بوستانلاله" to "Bustan-e Laleh",
)

fun main() {
    val files = listOf(
        "train_timetable_1.json",
        "train_timetable_2.json",
        "train_timetable_3.json",
        "train_timetable_4.json",
        "train_timetable_5.json",
        "train_timetable_6.json",
        "train_timetable_7.json",
        "train_timetable_branch_1.json",
        "train_timetable_branch_4.json",
        "train_timetable_branch_5.json"
    )

    for (fileName in files) {
        val file = File("${RES_PATH}$fileName")
        if (!file.exists()) {
            println("$fileName not found")
            continue
        }

        var content = file.readText()

        for ((faName, enName) in stationNameMapper) {
            val normalizedFa = normalizeName(faName)
            content = content.replace("\"$faName\"", "\"$enName\"")
            content = content.replace("\"$normalizedFa\"", "\"$enName\"")
        }

        file.writeText(content)
        println("updated $fileName")
    }
}